### ISSUE TITLE
Support multiple versions of Marionette

### ISSUE THREAD

**Issue by dithidi** [marionettejs/travis-ci-setup#1]
For testing environments such as marionette.inspector among others, it would be useful to have support for multiple versions of marionette.

**Comment by samccone** [comment]
yep :+1: will need to tweak this a touch to support it

@brentli1 are you interested in opening a PR?

**Comment by dithidi** [comment]
:+1: Sounds good

**Comment by samccone** [comment]
oh i got it

**Comment by samccone** [comment]
https://github.com/marionettejs/travis-ci-setup/pull/2 @brentli1
