### ISSUE TITLE
Can't find lodash

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/travis-ci-setup#3]
https://github.com/marionettejs/backbone.radio/pull/209

I'm getting this issue on the radio PR in travis and when running locally.

https://travis-ci.org/marionettejs/backbone.radio/jobs/57445121

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash'
```

lodash is a devDependency and used in the gulpfile.. any chance that's related?  Trying to figure out what else may be different between the implementation here and in marionette

**Comment by samccone** [comment]
yeah I think that is the issue

https://github.com/marionettejs/backbone.radio/pull/209/files#diff-b9e12334e9eafd8341a6107dd98510c9R14

it is unable to find lodash since we are moving the entry point file so it blows up, one solution would be to instead of a mv to use cp but just one thought...

**Comment by paulfalgout** [comment]
Yep that's it for sure.

Similarly, but the opposite is https://github.com/marionettejs/marionette.inspector/pull/257 which is complaining that underscore does not exist to copy into, so underscore has to be a npm dependency in the package.json for this script to work.

Related is that if you're using underscore or lodash as a dev dependency for use in gulp or the tests you'll have to make sure it works with the lowest version in the matrix since this'll blow the node_module away.

**Comment by paulfalgout** [comment]
Sooo this issue just got worse with npm 3 I think.
Both lodash v3 builds are failing https://github.com/marionettejs/backbone.marionette/pull/2801
And I'm pretty sure it's because some dev dependency somewhere is already loading a version of lodash... and since npm 3 is much more of a flat file system, the lodash version for the build dep is getting moved.

**Comment by samccone** [comment]
ohhhh this stinks :|
