### ISSUE TITLE
Lodash 4 really uses lodash.js

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/travis-ci-setup#6]
So we either need an `||` for the `if` or we also need to copy `lodash.js` with the `index.js` as `4.0` simply requires `lodash.js` inside the `index.js`

**Comment by paulfalgout** [comment]
@megawac thoughts?

We'll need to update this prior to testing https://github.com/marionettejs/backbone.marionette/pull/2889

Also, as this railroads the underscore used by the tests, the tests for Mn and babysitter / radio  will also need lodash 4 updates. :crying_cat_face:

**Comment by samccone** [comment]
:+1: I can help here

**Comment by paulfalgout** [comment]
Woo hoo!
